### ISSUE TITLE
Buildit file calls wrong lz4 folder

### ISSUE THREAD

**Issue by marshaburgess** [AndreasMartin72/mksqlite#10]
Dear @AndreasMartin72 ,

I am very new to Github and coding, so sorry if I get this wrong.

But in trying to build and mex mksqlite, I have found a bug in builit.m, line 72 should be, 
lz_src = 'c-blosc/internal-complibs/lz4-1.9.3/';

1.9.3 is what the current folder is, not 1.8..... as it was when importing from Git. 

Thank you

**Comment by a-ma72** [comment]
Thank you. buildit.m is deprecated and will be removed soon. I recommend to use CMake instead.

⁣Regards, Andreas​
