### ISSUE TITLE
Boolean value in file is not read properly

### ISSUE THREAD

**Issue by tomaszGorecki** [AndreasMartin72/mksqlite#2]
Hello,
Another problem I am facing now is that I am reading a table with boolean values (true and false). I know for sure from reading in the database with a php interface that the values in the table seem to be correct. 
However, when I am extracting these values with mksqlite with a call like follows

```
    res = mksqlite(['select ts, onoffstate from ' tableIdTmp{j} ' where ...']);
```

all the fields onoffstate in the structure res are empty instead of taking the true or false value.
I was using mksqlite 1.14 on MAC with matlab 2014b and also tried on Windows 7 with matlab 2014a and mksqlite 2.0
Any ideas why this happens ?

Best

Tomasz

**Comment by a-ma72** [comment]
Hi Tomasz,

seems you try to open a non-sqlite database? sqlite knows no boolean type, just INTEGER, TEXT, BLOB and REAL.
But you may easily cast it to an integer, that should work:
res = mksqlite(['select ts, CAST(onoffstate AS INTEGER) AS onoffstate from ' tableIdTmp{j} ' where ...']);

The "AS onoffstate" is necessary, bcause sqlite would return the result with column name "CAST(onoffstate..." which is not a proper MATLAB variable syntax, so mksqlite will change it to something like "CAST_onoffstate_...", not what you want.

Best
Andreas

**Comment by tomaszGorecki** [comment]
Hi,

It was a sqlite database and you were right. Just made a silly mistake.

Thx for the help

Tomasz

---- Andreas Martin a écrit ----

Hi Tomasz,

seems you try to open a non-sqlite database? sqlite knows no boolean type, just INTEGER, TEXT, BLOB and REAL.
But you may easily cast it to an integer, that should work:
res = mksqlite(['select ts, CAST(onoffstate AS INTEGER) AS onoffstate from ' tableIdTmp{j} ' where ...']);

The "AS onoffstate" is necessary, bcause sqlite would return the result with column name "CAST(onoffstate..." which is not a proper MATLAB variable syntax, so mksqlite will change it to something like "CAST_onoffstate_...", not what you want.

Best
Andreas
