### ISSUE TITLE
Writing non-ASCII characters to database

### ISSUE THREAD

**Issue by DrTK** [AndreasMartin72/mksqlite#3]
mksqlite is great! Thanks for all your work.
I've downloaded the latest version and compiled it on Ubuntu 14.04 LTS Linux using the `builtit.m` function.

Problem:
Whenever I try to write a  `char(i)` with `i>127` to database, I get an error: 
"`can't copy string in getstring()`".
This concerns "Umlaute" (ä,ö,ü) or degree sign °, or other things I unfortunately need to write to database.

The following code works perfectly under Windows, but fails on Linux:

```
function sqlite_test
    testDB = 'test.sqlite';    

    % Create the test table
    eval_sqlite('CREATE TABLE Test(id INTEGER PRIMARY KEY, msg TEXT)')
    % Insert something simple
    eval_sqlite('INSERT INTO Test (msg) VALUES ("Hello World")');
    % Here we get a problem on linux
    txt = 'Ähm';
    eval_sqlite(['INSERT INTO Test (msg) VALUES ("', txt, '")']);

    function out = eval_sqlite(command)
        mksqlite( 'open', testDB );
        out = mksqlite( command );
        mksqlite( 'close' );
    end

end
```

Unfortunately, I don't know much about mex files and c programming, however, it seems as if the error occurs somwhere around line 495 or 514 in `value.hpp`.

Any idea what's wrong here? Or any idea how I could manage to write ascii code above 127 to sqlite database?
Thanks in advance, Tobias

**Comment by a-ma72** [comment]
Hello Tobias, 
I guess it's in line 514 (you can test this by inserting a line _mexPrintf("In line 514\n");_ before the _mexErrMsgTxt(...)_ line)
Anyway, umlauts are often irksome under linux. It's good practice to set up MATLABs editor to use UTF-8 as default:
http://skweez.net/matlab-use-utf-8-encoding-as-default/
I will test tomorrow, how to set up the database...

Regards, Andreas

**Comment by a-ma72** [comment]
There is a hidden feature in MATLAB to set the editors encoding:
feature('DefaultCharacterSet', 'UTF-8')

With mksqlite you can control the implicit conversion by _mksqlite('convertUTF8', 0|1)_.

**Comment by DrTK** [comment]
Thanks for your super-fast reply!!, and for the hint to set default character set to UTF8.

I tried to run with proposed `mksqlite('convertUTF8', 0|1)` command, yet, I still get the `can't copy string in getstring()` - error :-(
Here's what I did:

```
% Open and set up test database
testDB = 'test.sqlite'; if exist(testDB, 'file'), delete(testDB); end  % Remove database from any previous run
mksqlite( 'open', testDB );
mksqlite( 'convertUTF8', 1 );
mksqlite( 'CREATE TABLE Test(id INTEGER PRIMARY KEY, msg TEXT)' )

% Writing char(i>127) will still cause an error:
try
    % Try to write degree symbol ° to database
    mksqlite(['INSERT INTO Test (msg) VALUES ("', char(176), '")']);   

catch Me
    disp(Me.getReport)
    disp('Error -> closing database');
    mksqlite('close');    % At least close the database
end 
```

**Comment by a-ma72** [comment]
Hello Tobias,

indeed you've found a bug, thank you!

With the current bugfix (see last commit) this code works on my system:

```
clear all
sql('open','test.db');
sql('convertUTF8',1); 
feature('DefaultCharacterSet','UTF-8')
sql('create table foo (bar)');
sql('insert into foo values ("Text")');
sql('insert into foo values ("äöüß")');
sql(0,'close');
```

Checked with a sql data browser, the correct values have been written.

Regards, Andreas

**Comment by DrTK** [comment]
Awesome!! Thank you so much!!
I succressfully build and tested your last commit with MatlabR2015b, MatlabR2010a, and MatlabR2010b on Ubunutu 14.04 LTS. Works without any problems now.
Again, thank you so much for your quick help!!

**Comment by a-ma72** [comment]
Last code example throws no error, but is malformed. Use either 
```
clear all
sql('open','test.db');
sql('convertUTF8',0); 
feature('DefaultCharacterSet','UTF-8')
sql('create table foo (bar)');
sql('insert into foo values ("Text")');
sql('insert into foo values ("äöüß")');
sql(0,'close');
```
or
```
clear all
sql('open','test.db');
sql('convertUTF8',1); 
feature('DefaultCharacterSet','windows-1252')
sql('create table foo (bar)');
sql('insert into foo values ("Text")');
sql('insert into foo values ("äöüß")');
sql(0,'close');
```

Regards, Andreas
