### ISSUE TITLE
Non-ASCII characters - Again

### ISSUE THREAD

**Issue by DrTK** [AndreasMartin72/mksqlite#7]
I recently downloaded the latest mksqlite version and compiled it using MATLAB R2015b on LINUX Ubuntu 16.04 LTS - everything worked like a charm.

Yet, I had some problems again when write Non-ASCII characters:
When running the code snippet we used last time (compare to https://github.com/AndreasMartin72/mksqlite/issues/3)
```
clear all
sql('open','test.db');
sql('convertUTF8', 1); 
feature('DefaultCharacterSet','UTF-8')
sql('create table foo (bar)');
sql('insert into foo values ("Text")');
sql('insert into foo values ("äöüß")');
sql(0,'close');
```
the *Umlaute* "äöüß" aren't correctly written to 'test.db'.

Interestingly, when changing the 'convertUTF8' line to
```
sql('convertUTF8', 0); 
```
then everything works again. I just wanted to share this finding in case anybody else is running into the same issue.

Thanks again for all your work and keeping everything up to date! mksqlite is awesome!
Tobias

**Comment by a-ma72** [comment]
Yes this is defined behavior, so on Windows OS you get the same result with that code above.
Here is the reason why:
mksqlite doesn't "know" which encoding is used by your editor, but SQLite always expects UTF8 encoding.
So with sql('convertUTF8', 1) you tell mksqlite that you intend to give "windows-1252" encoded strings, and mksqlite has to convert it to UTF8.
When your editor works with UTF8 encoding already, this option is misplaced. The string would be converted twice and gives not the result you expect in the end.

Regards, Andreas
